# Generated by Django 3.2.5 on 2021-07-29 12:14

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20210729_1320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='default/avatar.png', upload_to=accounts.models.user_directory_path),
        ),
    ]
