# Generated by Django 3.2.5 on 2021-07-29 13:11

import accounts.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0011_alter_album_parent_album'),
        ('accounts', '0004_alter_profile_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='profile',
        ),
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, default='default/avatar.png', upload_to=accounts.models.user_directory_path),
        ),
        migrations.AlterField(
            model_name='profile',
            name='portfolio',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.PROTECT, to='album.album'),
        ),
    ]
