# Generated by Django 3.2.5 on 2021-07-31 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_profile_portfolio'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='name',
            field=models.CharField(default='Name', max_length=100),
            preserve_default=False,
        ),
    ]
