# Generated by Django 3.2.5 on 2021-08-03 09:58

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_rename_user_profile_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, default='default/avatar.png', upload_to=accounts.models.user_directory_path, validators=[accounts.models.validate_image]),
        ),
    ]
