# Generated by Django 3.2.5 on 2021-08-03 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_profile_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='payment_info',
            field=models.TextField(default='PAYMENT'),
            preserve_default=False,
        ),
    ]
