# Generated by Django 3.2.5 on 2021-08-09 10:55

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20210808_2318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='default/avatar.png', upload_to=accounts.models.user_directory_path, validators=[accounts.models.validate_image]),
        ),
    ]
