# Generated by Django 3.2.5 on 2021-09-21 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_alter_profile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='payment_info',
            field=models.TextField(blank=True),
        ),
    ]
