# Generated by Django 3.2.5 on 2021-07-25 12:11

import album.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0003_auto_20210725_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(height_field='height', max_length=50, upload_to=album.models.user_directory_path, width_field='width'),
        ),
    ]
