# Generated by Django 3.2.5 on 2021-07-25 12:12

import album.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0004_alter_image_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(height_field='height', upload_to=album.models.user_directory_path, width_field='width'),
        ),
    ]
