# Generated by Django 3.2.5 on 2021-07-25 18:47

import album.models
import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0006_alter_image_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(height_field='height', storage=django.core.files.storage.FileSystemStorage(base_url='/protected', location='D:\\Repositories\\ticket-app\\protected'), upload_to=album.models.user_directory_path, width_field='width'),
        ),
    ]
