# Generated by Django 3.2.5 on 2021-07-29 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0009_auto_20210726_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='parent_album',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='album.album'),
        ),
    ]
