# Generated by Django 3.2.5 on 2021-08-04 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0012_album_is_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='title',
            field=models.CharField(default='file', max_length=100),
            preserve_default=False,
        ),
    ]
