# Generated by Django 3.2.5 on 2021-08-07 10:39

import album.models
import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0013_image_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(height_field='height', storage=django.core.files.storage.FileSystemStorage(base_url='/test_data/protected/', location='D:\\Repositories\\ticket-app\\test_data\\protected'), upload_to=album.models.user_directory_path, width_field='width'),
        ),
    ]
