# Generated by Django 3.2.5 on 2021-08-10 15:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0014_alter_image_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
