# Generated by Django 3.2.5 on 2021-08-19 10:53

import album.models
import core.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0016_alter_image_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(height_field='height', storage=core.storage_backends.PrivateMediaStorage, upload_to=album.models.user_directory_path, width_field='width'),
        ),
    ]
