# Generated by Django 3.2.5 on 2021-08-02 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_remove_order_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cost',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='currency',
            field=models.CharField(choices=[('PLN', 'Polish Zloty'), ('EUR', 'Euro'), ('USD', 'United States Dollar')], default='EUR', max_length=3),
        ),
    ]
