# Generated by Django 3.2.5 on 2021-08-07 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Canceled'), (1, 'Rejected'), (2, 'Waiting for acceptance'), (3, 'Accepted'), (4, 'Waiting for payment'), (5, 'Payment received'), (6, 'Finished')], default=2),
        ),
    ]
